// to check whether the given letter is a vowel or a consonant.//
#include<iostream.h>
#include<conio.h>
void main()
{clrscr();
 char ch;
 cin>>ch;
 if (ch=='A'|| ch=='E'|| ch=='I'||ch=='O'||ch=='U'||  ch=='a'||ch=='e'||ch=='i'||ch=='o'||ch=='u')
 {cout<<"it is a vowel";
 }
 else if(ch!='A'|| ch!='E'|| ch!='O'|| ch !='U'|| ch!='I'||ch=='a'||ch=='e' ||ch=='i'||ch=='o'||ch=='u')
 { cout<<"it is consonant";
 }
  getch();
  }


